version: '3'

services:
  fastapi:
    build:
      context: .
    ports:
      - "80:80"
    depends_on:
      - alembic

  alembic:
    build:
      context: .
    entrypoint: ["alembic", "upgrade", "head"]

  test:
    build:
      context: .
    command: ["pytest"]
    depends_on:
      - fastapi
