version: "3"
services:
  api:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
  db:
    image: sqlite
    volumes:
      - /path/to/your/sqlite/database/file:/app/database.db
